import { ChevronDown, Circle, Loader2, Trash, Twitter } from "lucide-react"

import {
  BiMovie,
  BiTv,
  BiCheckSquare,
  BiListOl,
  BiNews,
  BiStar,
  BiTrophy,
} from "react-icons/bi"
import { ImBook } from "react-icons/im"
import { IoGameController } from "react-icons/io5"

import {
  FaAndroid,
  FaApple,
  FaAppleAlt,
  FaCoffee,
  FaLinux,
  FaPlaystation,
  FaWindows,
  FaXbox,
  FaFacebook,
  FaInstagram,
  FaYoutube,
  FaEnvelope,
  FaLinkedinIn,
  FaPinterestP,
  FaRedditAlien,
  FaTelegramPlane,
  FaWhatsapp,
} from "react-icons/fa"

import {
  MdAnalytics,
  MdDiscount,
  MdStore,
  MdAddShoppingCart,
  MdImage,
  MdDiamond,
  MdDownload,
  MdOutlineHome,
  MdOutlineAdsClick,
  MdOutlineArticle,
  MdOutlineComment,
  MdOutlineCreditCard,
  MdOutlinePermMedia,
  MdOutlineSettings,
  MdOutlineTopic,
  MdSupervisedUserCircle,
  MdDarkMode,
  MdLightMode,
  MdAccessTime,
  MdClose,
  MdAccountCircle,
  MdOutlineMoreVert,
  MdChevronRight,
  MdChevronLeft,
  MdOutlineMenu,
  MdOutlineBrokenImage,
  MdLogin,
  MdOutlineKeyboardArrowDown,
  MdOutlineModeEdit,
  MdOutlineDelete,
  MdOutlineVisibility,
  MdOutlineArrowBack,
  MdOutlineArrowForward,
  MdPerson,
  MdDashboard,
  MdLogout,
  MdOutlineEditNote,
  MdOutlineSave,
  MdOutlineSearch,
  MdOutlineCheck,
  MdOutlineVisibilityOff,
  MdOutlineAdd,
  MdOutlineViewSidebar,
  MdContentCopy,
  MdCurrencyExchange,
  MdUploadFile,
  MdCode,
  MdUpdate,
  MdCategory,
  MdFolder,
  MdVpnKey,
  MdDeveloperBoard,
  MdHelpOutline,
} from "react-icons/md"

export const Icon = {
  AccessTime: MdAccessTime,
  Account: MdAccountCircle,
  Add: MdOutlineAdd,
  Ads: MdOutlineAdsClick,
  Analytics: MdAnalytics,
  Android: FaAndroid,
  Apple: FaApple,
  AppleAlt: FaAppleAlt,
  ArrowBack: MdOutlineArrowBack,
  ArrowForward: MdOutlineArrowForward,
  Article: MdOutlineArticle,
  Book: ImBook,
  BrokenImage: MdOutlineBrokenImage,
  Cart: MdAddShoppingCart,
  Category: MdCategory,
  Check: MdOutlineCheck,
  CheckSquare: BiCheckSquare,
  ChevronLeft: MdChevronLeft,
  ChevronRight: MdChevronRight,
  ChevronDown: ChevronDown,
  Circle: Circle,
  Close: MdClose,
  Code: MdCode,
  Coffe: FaCoffee,
  Comment: MdOutlineComment,
  Copy: MdContentCopy,
  CreditCard: MdOutlineCreditCard,
  Currency: MdCurrencyExchange,
  Dashboard: MdDashboard,
  Developer: MdDeveloperBoard,
  Diamond: MdDiamond,
  Discount: MdDiscount,
  Download: MdDownload,
  Delete: MdOutlineDelete,
  EditNote: MdOutlineEditNote,
  Email: FaEnvelope,
  Facebook: FaFacebook,
  Folder: MdFolder,
  Game: IoGameController,
  Help: MdHelpOutline,
  Home: MdOutlineHome,
  Image: MdImage,
  Instagram: FaInstagram,
  KeyboardArrowDown: MdOutlineKeyboardArrowDown,
  Linkedin: FaLinkedinIn,
  Linux: FaLinux,
  ListOl: BiListOl,
  Login: MdLogin,
  Logout: MdLogout,
  Media: MdOutlinePermMedia,
  Menu: MdOutlineMenu,
  ModeEdit: MdOutlineModeEdit,
  MoreVert: MdOutlineMoreVert,
  Moon: MdDarkMode,
  Movie: BiMovie,
  News: BiNews,
  Person: MdPerson,
  Pinterest: FaPinterestP,
  PlayStaton: FaPlaystation,
  Reddit: FaRedditAlien,
  Save: MdOutlineSave,
  Settings: MdOutlineSettings,
  Search: MdOutlineSearch,
  Shop: MdStore,
  Spinner: Loader2,
  Star: BiStar,
  Sun: MdLightMode,
  Telegram: FaTelegramPlane,
  Topic: MdOutlineTopic,
  Trash: Trash,
  Trophy: BiTrophy,
  TV: BiTv,
  Twitter: Twitter,
  Update: MdUpdate,
  UploadFile: MdUploadFile,
  Users: MdSupervisedUserCircle,
  ViewSidebar: MdOutlineViewSidebar,
  Visibility: MdOutlineVisibility,
  VisibilityOff: MdOutlineVisibilityOff,
  VpnKey: MdVpnKey,
  Xbox: FaXbox,
  WhatsApp: FaWhatsapp,
  Windows: FaWindows,
  Youtube: FaYoutube,
}
